# -*- coding: utf-8 -*-
"""rai_AED

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1hHQgcTLv8Z1QVgEci8Cp1HdFq49OWl

Raihana Asma Amani
G1401221039
AED PERTEMUAN 8

#Membaca data bentuk excel
"""

import pandas as pd

data_file = pd.read_excel('/content/bahan_data (1).xlsx')
data_file

"""# Grafik Line Plot"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.lineplot(x="Produk Domestik Regional Bruto", y="Indeks Kebahagiaan", data=data_file)

# setting the title using Matplotlib
plt.title('Line plot Produk Domestik Regional dengan Indeks Kebagiaan Provinsi Tahun 2021')
plt.xlabel('Produk Domestik Regional')
plt.ylabel('Indeks Kebahagiaan')

plt.show()

"""Berdasarkan grafik line plot di atas diperoleh informasi antara lain :


1.   Tren Indeks Kebahagian bertambah dengan Produk Domestik Regional yang meningkat.
Namun, penting untuk mempertimbangkan faktor-faktor lain yang juga memengaruhi kebahagiaan untuk mendapatkan pemahaman yang lebih lengkap tentang tingkat kebahagiaan di suatu provinsi.

# Grafik Scatter Plot
"""

from scipy.stats import pearsonr

# Mengatur warna secara manual
color = {"Sumatera": "blue", "Jawa": "yellow", "Kalimantan" : "purple","Sulawesi": "red", "Papua" : "green"}

# draw scatterplot
sns.scatterplot(x='Produk Domestik Regional Bruto', y='Indeks Kebahagiaan', data=data_file, hue='Pulau', palette=color)
sns.regplot(x='Produk Domestik Regional Bruto', y='Indeks Kebahagiaan', data=data_file, scatter=False)

# Hitung nilai korelasi Pearson
correlation_coefficient, p_value = pearsonr(data_file['Produk Domestik Regional Bruto'], data_file['Indeks Kebahagiaan'])

# Tampilkan nilai korelasi pada plot
correlation_text = f'Pearson Correlation: {correlation_coefficient:.2f}'
plt.text(0.5, 0.9, correlation_text, horizontalalignment='center', verticalalignment='center', transform=plt.gca().transAxes, fontsize=10)

plt.title('Hubungan Produk Domestik Regional terhadap Indeks Kebagiaan Provinsi Tahun 2021')
plt.xlabel('Produk Domestik Regional')
plt.ylabel('Indeks Kebahagiaan')

plt.show()

"""Berdasarkan grafik Scatter plot diatas diperoleh informasi bahwa :


1.   Hubungan antara Produk Domestik Regional dengan Indeks Kebahagiaan adalah linear positif. Hal tersebut menyatakan bahwa semakin tinggi Produk Domestik Regional di suatu provinsi maka Indeks Kebahagiaan di provinsi tersebut juga semakin tinggi.
2.   Pulau yang memiliki PDR dan IK yang cukup tinggi terdapat di Pulau Jawa sedangkan yang cukup rendah terdapat di Pulau Papua

# Diagram Gelembung
"""

import seaborn as sns
import matplotlib.pyplot as plt


# Create PairGrid
plot = sns.PairGrid(data_file)
plot.map_upper(sns.scatterplot)  # Scatter plot di segitiga bagian atas
plot.map_lower(sns.scatterplot)  # Scatter plot di segitiga bagian bawah
plot.map_diag(plt.hist)  # Plot histogram di diagonal

plt.show()